// Backwards-compat barrel — all implementations live in src/repositories/
// Import directly from src/repositories/ in new code.
export * from '../repositories'

// Re-export canonical types so existing `import { Vendor } from '../lib/database'` keeps working
export type {
  UserRole,
  UserStatus,
  User,
  Profile,
  Tourist,
  UserProfile,
  UserPreferences,
  VendorStatus,
  VendorTier,
  Vendor,
  ServiceStatus,
  ServiceCategory,
  Service,
  Flight,
  ServiceDeleteRequest,
  BookingStatus,
  Booking,
  TransactionType,
  TransactionStatus,
  Transaction,
  Wallet,
  PricingTier,
  ServicePricingOverride,
  PaymentCalculation,
  PricingPreview,
  TierCommissionResolve,
  VisitorSession,
  ServiceLike,
  ServiceReview,
  VisitorActivity,
  ServiceViewLog,
  PartnerRequest,
  Partner,
} from '../types'
